<?php

/**
 * @wordpress-plugin
 * Plugin Name:       Kntnt Proxy Sitemap for Slim SEO
 * Plugin URI:        https://www.kntnt.com/
 * Description:       Adds the sitemap of a proxied site to the sitemap generated by Slim SEO.
 * Version:           1.0.0
 * Author:            Thomas Barregren
 * Author URI:        https://www.kntnt.com/
 * License:           GPL-3.0+
 * License URI:       http://www.gnu.org/licenses/gpl-3.0.txt
 */

add_filter( 'slim_seo_sitemap_post_types', function ( $post_types ) {
    
    // Get URL to the sitemap of the proxied site.
    $http = isset( $_SERVER['HTTPS'] ) && 'on' === $_SERVER['HTTPS'] ? 'https://' : 'http://';
    $domain = $_SERVER['HTTP_HOST'];
    $uri = $_SERVER['REQUEST_URI'];
    $proxy_sitemap_url = apply_filters( 'kntnt-slim-seo-proxy-sitemap-url', "$http$domain$uri/magasinet/", $http, $domain, $uri );

    // Get the the sitemap of the proxied site.
    $sitemap = file_get_contents( 'https://www.kntnt.se/magasinet/sitemap.xml' );
    
    if ( false !== $sitemap ) {
        
        // Echo <sitemap><loc>…</loc></sitemap> of the sitemap of the proxied site.
        preg_match_all( '`<sitemap>\s*<loc>[^>]+</loc>\s*</sitemap>`', $sitemap, $matches );
        echo implode( "\n", $matches[0] ) . "\n";
    }

    // In lack of an action, a filter was misused, and therefore the filtered value must be returned unchanged.
    return $post_types;

});
